//! Load control: the rotary encoder that browses the library (decoded in PIO)
//! and the button that loads the highlighted track into the selected deck.

use core::sync::atomic::Ordering;
use defmt::info;
use embassy_rp::{
    Peri,
    gpio::{Input, Pull},
    peripherals::PIO0,
    pio::{
        Common, Config as PioConfig, Direction as PioDirection, FifoJoin, PioPin, ShiftDirection,
        StateMachine, program,
    },
    pio_programs::clock_divider::calculate_pio_clock_divider,
};

use crate::{
    midi::{MidiMsg, send_midi},
    state::SELECTED_DECK,
};

// Encoder lines are sampled every ~5 µs
const ENCODER_PIO_CLOCK_HZ: u32 = 1_000_000;
const QUARTER_STEPS_PER_DETENT: i8 = 2;
// Used for ignore bounces on direction jumps
const QUADRATURE_TABLE: [i8; 16] = [
    0, 1, -1, 0, //
    -1, 0, 0, 1, //
    1, 0, 0, -1, //
    0, -1, 1, 0, //
];

/// Starts the state machine for the encoder
// Logic by AI
pub(crate) fn init_encoder(
    common: &mut Common<'static, PIO0>,
    mut sm: StateMachine<'static, PIO0, 0>,
    pin_clk: Peri<'static, impl PioPin>,
    pin_dt: Peri<'static, impl PioPin>,
) -> StateMachine<'static, PIO0, 0> {
    let prg = program::pio_asm!(
        "start:",
        "    mov isr, null",
        "    in pins, 2",
        "    mov x, isr",
        "    jmp x!=y, changed",
        "    jmp start",
        "changed:",
        "    mov y, x",
        "    push",
    );
    let prg = common.load_program(&prg.program);

    let mut pin_clk = common.make_pio_pin(pin_clk);
    let mut pin_dt = common.make_pio_pin(pin_dt);
    pin_clk.set_pull(Pull::Up);
    pin_dt.set_pull(Pull::Up);
    sm.set_pin_dirs(PioDirection::In, &[&pin_clk, &pin_dt]);

    let mut cfg = PioConfig::default();
    cfg.set_in_pins(&[&pin_clk, &pin_dt]);
    cfg.fifo_join = FifoJoin::RxOnly;
    cfg.shift_in.direction = ShiftDirection::Left;
    cfg.clock_divider = calculate_pio_clock_divider(ENCODER_PIO_CLOCK_HZ);
    cfg.use_program(&prg, &[]);

    sm.set_config(&cfg);
    sm.set_enable(true);
    sm
}

/// Async task reading the rotary encoder
// Function generated by AI
#[embassy_executor::task]
pub(crate) async fn load_encoder_task(mut sm: StateMachine<'static, PIO0, 0>) {
    let mut state = (sm.rx().wait_pull().await & 0b11) as u8;
    let mut quarter: i8 = 0;

    info!("Encoder ready.");

    loop {
        let new_state = (sm.rx().wait_pull().await & 0b11) as u8;
        let delta = QUADRATURE_TABLE[((state << 2) | new_state) as usize];
        state = new_state;

        if delta == 0 {
            continue;
        }
        quarter += delta;

        if quarter.abs() < QUARTER_STEPS_PER_DETENT {
            continue;
        }
        let data = if quarter > 0 { 1 } else { 0 };
        quarter = 0;

        send_midi(MidiMsg::ControlChange {
            cc: 0x08,
            value: if data == 1 { 0x01 } else { 0x7F },
        });
    }
}

/// Async task reading load button press
#[embassy_executor::task]
pub(crate) async fn load_button_task(mut button: Input<'static>) {
    loop {
        button.wait_for_low().await;
        // Note 0x02 or 0x03
        let note = 0x02 + SELECTED_DECK.load(Ordering::Relaxed);
        send_midi(MidiMsg::NoteOn {
            note,
            velocity: 0x7F,
        });

        button.wait_for_high().await;
        send_midi(MidiMsg::NoteOff { note });
    }
}
